#!/usr/bin/env php
<?php

require "vendor/autoload.php";

class TestJob extends \ajumamoro\Job
{
    private $id, $delay;
    
    public function __construct($id, $delay)
    {
        $this->id = $id;
        $this->delay = $delay;
    }

    public function go()
    {
        sleep($this->delay);
        $this->log("Going with Job {$this->id}");
    }

}

$queue = ajumamoro\Queue::connectBroker([
    'driver' => 'redis',
    'scheme' => 'tcp',
    'host' => '127.0.0.1'
]);

for($i = 0; $i < 20; $i++)
{
    $queue->add(new TestJob($i, rand(5, 10)));
}

